### ISSUE TITLE
Trying to use this library

### ISSUE THREAD

**Issue by chemeng** [teogramm/oasth#1]
Hello, I'm a novice in kotlin (never used it before) but I'm trying to use this package and I can't seem to get it to work. Can you provide installation instructions?

I simply tried navigating to the `src/main/kotlin` folder, open a kotlin console and do `import xyz.teogramm.oasth` but I get 
```
error: packages cannot be imported
import xyz.teogramm.oasth
                    ^
```

**Comment by teogramm** [comment]
There was an oversight in the import statement. It should be ```import xyz.teogramm.oasth.Oasth```. 

Thanks for pointing this out, I have fixed it.

**Comment by chemeng** [comment]
Hmm, I still can't get this to work..

<img width="264" alt="image" src="https://github.com/teogramm/oasth/assets/1289113/98f54dde-b40d-4afd-adb7-bac6dbbcfe25">

**Comment by teogramm** [comment]
The easiest way to use the library is alongside a build system such as Maven or Gradle and an IDE (I use IntelliJ).

I am not familiar with the Kotlin interactive shell, however I assume that in order to import the library you have to add it to your Java CLASSPATH.
